name: "Texecom Connect"
version: "0.5.8"
slug: "texecom-connect"
description: "This is a python module that connects Texecom Alarm systems to Home Assistant with MQTT"
url: "https://github.com/Sjoerdfc/texecom-connect/"
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  TEXHOST: "10.0.0.20"
  TEXPORT: 10001
  UDLPASSWORD: "1234"
  BROKER_URL: "core-mosquitto"
  BROKER_USER: ""
  BROKER_PASS: ""
  MQTT_ROOT_TOPIC: "homeassistant"
  AREA_1_ENABLED: true
  AREA_2_ENABLED: false
  AREA_3_ENABLED: false
  AREA_4_ENABLED: false
  PART_ARM_1: "ARM_NIGHT"
  PART_ARM_2: "ARM_HOME"
  PART_ARM_3: "ARM_VACATION"
schema:
  TEXHOST: "str"
  TEXPORT: "int"
  UDLPASSWORD: "str"
  BROKER_URL: "str"
  BROKER_USER: "str?"
  BROKER_PASS: "str?"
  MQTT_ROOT_TOPIC: "str"
  AREA_1_ENABLED: "bool"
  AREA_2_ENABLED: "bool"
  AREA_3_ENABLED: "bool"
  AREA_4_ENABLED: "bool"
  PART_ARM_1: "str?"
  PART_ARM_2: "str?"
  PART_ARM_3: "str?"
  ZONE_1_CLASS: "str?"
  ZONE_2_CLASS: "str?"
  ZONE_3_CLASS: "str?"
  ZONE_4_CLASS: "str?"
  ZONE_5_CLASS: "str?"
  ZONE_6_CLASS: "str?"
  ZONE_7_CLASS: "str?"
  ZONE_8_CLASS: "str?"
  ZONE_9_CLASS: "str?"
  ZONE_10_CLASS: "str?"
  ZONE_11_CLASS: "str?"
  ZONE_12_CLASS: "str?"
  ZONE_13_CLASS: "str?"
  ZONE_14_CLASS: "str?"
  ZONE_15_CLASS: "str?"
  ZONE_16_CLASS: "str?"
image: "sjoerdfc/texecom-connect-ha-{arch}"
